### ISSUE TITLE
iOS 13.5, A12 can not use

### ISSUE THREAD

**Issue by hanqingice** [twotreeszf/NoBackgroundPhotoAccess#1]
iOS 13.5, A12

dlopen_preflight(/Library/PreferenceBundles/NoBackgroundPhotoAccessPrefer.bundle/NoBackgroundPhotoAccessPrefer): no suitable image found.  Did find:
	/Library/PreferenceBundles/NoBackgroundPhotoAccessPrefer.bundle/NoBackgroundPhotoAccessPrefer: arm64 dylibs cannot be loaded into arm64e processes
	/Library/PreferenceBundles/NoBackgroundPhotoAccessPrefer.bundle/NoBackgroundPhotoAccessPrefer: arm64 dylibs cannot be loaded into arm64e processes

**Comment by twotreeszf** [comment]
Ok, I will solve this  as soon as possible, the cause of the issue has been found

**Comment by twotreeszf** [comment]
Hello, please download 1.1.3 in the release section and have a try, then give me a feedback.

**Comment by twotreeszf** [comment]
Support for iOS 12.0–13.7 has been completed.
Please use the 1.1.3 version in the release section and install it with filza, and then tell me the feedback.

**Comment by hanqingice** [comment]
I've installed the 1.1.3 and it seems be worked, but I don't know whether like that, many tks!

**Comment by Cregin** [comment]
请问是如何修复这个问题的？我现在的插件也是无法加载PreferenceBundles
