### ISSUE TITLE
ios13.3 A13 不能使用显示arm64e

### ISSUE THREAD

**Issue by qwer12345uui** [twotreeszf/NoBackgroundPhotoAccess#2]
1.1.2到初行发布都尝试过

**Comment by twotreeszf** [comment]
周一解决，稍等。

qwer12345uui ***@***.***>于2021年10月17日 周日14:56写道：

**Comment by twotreeszf** [comment]
你好，请下载 1.1.3 试试看，麻烦反馈一下好了没有

**Comment by twotreeszf** [comment]
Support for iOS 12.0–13.7 has been completed.
Please use the 1.1.3 version in the release section and install it with filza, and then tell me the feedback.

**Comment by qwer12345uui** [comment]
抱歉刚刚才看到，已经可以正常使用👍
